export const FETCH_SERVICES_REQUEST = 'FETCH_SERVICES_REQUEST';
export const FETCH_SERVICES_FAILURE = 'FETCH_SERVICES_FAILURE';
export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS';
export const ADD_SERVICE_REQUEST = 'ADD_SERVICE_REQUEST';
export const ADD_SERVICE_FAILURE = 'ADD_SERVICE_FAILURE';
export const ADD_SERVICE_SUCCESS = 'ADD_SERVICE_SUCCESS';

export const CHANGE_SERVICE_FIELD = 'CHANGE_SERVICE_FIELD';
export const CHANGE_EDIT_SERVICE_FIELD = 'CHANGE_EDIT_SERVICE_FIELD'

export const REMOVE_SERVICE_API = 'REMOVE_SERVICE_API';


export const EDIT_SERVICE_REQUEST = 'EDIT_SERVICE_REQUEST';
export const EDIT_SERVICE_FAILURE = 'EDIT_SERVICE_FAILURE';
export const EDIT_SERVICE_SUCCESS = 'EDIT_SERVICE_SUCCESS';

export const UPDATE_SERVICE_REQUEST = 'UPDATE_SERVICE_REQUEST';
export const UPDATE_SERVICE_FAILURE = 'UPDATE_SERVICE_FAILURE';
export const UPDATE_SERVICE_SUCCESS = 'UPDATE_SERVICE_SUCCESS';